# Changes here will be overwritten by Copier
_commit: v3.2.1
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GPL-3.0
github_repository_name: private-assistant-alarm-scheduler-skill-py
github_username: stkr22
project_description: A Python skill for scheduling and managing persistent alarms
    with support for recurring events, using cron expressions and webhook integration
    for immediate triggering external alarms.
project_name: Private Assistant Alarm Scheduler Skill
publish_to_pypi: false
python_package_distribution_name: private-assistant-alarm-scheduler-skill
python_package_import_name: private_assistant_alarm_scheduler_skill
python_package_version: 1.2.1
use_containers: true
