[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "private-assistant-alarm-scheduler-skill"
version = "1.2.1"
description = "A Python skill for scheduling and managing persistent alarms with support for recurring events, using cron expressions and webhook integration for immediate triggering external alarms."
authors = [
    { name = "stkr22", email = "stkr22@github.com" }
]
readme = "README.md"
license = { text = "GNU General Public License v3.0" }

keywords = []
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Programming Language :: Python",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Home Automation",
]

requires-python = ">=3.11,<3.13"
dependencies = [
    "private-assistant-commons~=3.0.0",
    "pydantic~=2.9.2",
    "sqlmodel~=0.0.22",
    "httpx~=0.28.0",
    "jinja2~=3.1.4",
    "croniter~=6.0.0",
    "asyncpg~=0.30.0",
    "typer~=0.15.0",
]

[project.scripts]
private-assistant-alarm-scheduler-skill = "private_assistant_alarm_scheduler_skill.main:app"


[dependency-groups]
dev = [
    "ruff~=0.8.0",
    "mypy~=1.17.0",
    "pytest~=8.4.1",
    "pytest-cov~=6.2.1",
    "types-croniter~=5.0.1.20241205",
    "respx~=0.22.0",
    "aiosqlite~=0.21.0",
]

[tool.ruff]
target-version = "py312"
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "UP",   # pyupgrade
    "N",    # pep8-naming
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib
    "ERA",  # eradicate
]
ignore = ["E203"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra -q"

[tool.coverage.run]
source = ["private_assistant_alarm_scheduler_skill"]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
]
